
services:

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: "unless-stopped"

  redis:
    image: redislabs/redisearch:2.8.8
    ports:
      - 6379:6379
    restart: "unless-stopped"

  # weaviate:
  #   image: semitechnologies/weaviate:1.20.5
  #   ports:
  #   - 8090:8080
  #   restart: on-failure:0
  #   environment:
  #     QUERY_DEFAULTS_LIMIT: 25
  #     AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
  #     PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
  #     DEFAULT_VECTORIZER_MODULE: 'none'
  #     CLUSTER_HOSTNAME: 'node1'

