
services:

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: "unless-stopped"

  redis:
    image: redislabs/redisearch:2.8.8
    ports:
      - 6379:6379
    restart: "unless-stopped"

