
services:

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:11434
      - verbose=true
    pull_policy: always
    tty: true
    restart: "unless-stopped"

  neo4j:
    image: neo4j:5.20.0
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
    restart: "unless-stopped"

  fhirg:
    image: beapen/fhirg:latest
    ports:
      - 8080:8080
    environment:
      - spring.neo4j.uri=bolt://neo4j:7687