
services:

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:11434
      - verbose=true
    pull_policy: always
    tty: true
    restart: "unless-stopped"

  redis:
    image: redislabs/redisearch:2.8.8
    ports:
      - 6379:6379
    restart: "unless-stopped"
    volumes:
      - redis-data:/data

volumes:
  redis-data: ~

