
services:

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:11434
      - verbose=true
    pull_policy: always
    tty: true
    restart: "unless-stopped"

  neo4j:
    image: neo4j:5.16.0
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_auth__enabled=false
      - NEO4J_dbms_databases_default__to__read__only:false
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4j_PLUGINS='["apoc", "graph-data-science"]'
    restart: "unless-stopped"


