
services:

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:11434
      - verbose=true
    pull_policy: always
    tty: true
    restart: "unless-stopped"

  neo4j:
    image: neo4j:5.1-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc", "graph-data-science", "n10s"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*,n10s.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*,gds.*,n10s.*
    restart: "unless-stopped"
    # volumes:
    #   - neo4j-data:/data


  fhirg:
    image: beapen/fhirg:latest
    ports:
      - 8080:8080
    environment:
      - spring.neo4j.uri=bolt://neo4j:7687

# volumes:
#   neo4j-data: ~